### PR TITLE
XDR-4399: Bump terraform version to 1.2.5

### PR DESCRIPTION
**Pull request by chrisjaimon2012**

### CODE REVIEW

**Review by nicholascwd — APPROVED** [review]

**Review by nicholascwd — DISMISSED** [review]
precommit failure

**Comment by chrisjaimon2012** [comment]
no idea why its failing
@nicholascwd @GerardSetho

**Comment by chrisjaimon2012** [comment]
I have a hacky fix, just to get avoid the PANIC on tfsec

**Comment by chrisjaimon2012** [comment]
https://github.com/aquasecurity/tfsec/issues/1969

**Review by GerardSetho — APPROVED** [review]

**Pull request merged**
